import Head from 'next/head'
import Link from"next/link"
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header class ="navigation-menu">
        <nav>
          <ul>
          <Link href='/'><li><h2>CRIT</h2></li></Link>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/nft'><a><li>NFT</li></a></Link>
          <Link href='/blog'><a><li>BLog</li></a></Link>
          <Link href='/contact'><a><li>Contact</li></a></Link>
          <Link href='/wallet'><a><li>Wallet</li></a></Link>
          <button>BUY NOW</button>
          </ul>
        </nav>
      </header>
          
    <main>
      {/* <DIV class="banner"> */}
      <h1>CRIT</h1>
      <h1>NFT Collection</h1>
      <p class ="banner-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut lacinia dolor. Cras et lacus sed est pulvinar ornare at at tortor. Suspendisse potenti. Ut elementum tempor erat, volutpat dignissim ipsum tristique sed. Etiam risus nibh, scelerisque a efficitur dignissim, suscipit eu tortor.</p>
      <Link href='/'><h2>BUY NOW</h2></Link>  
      {/* </DIV>  */}
    </main>

      <footer>

      </footer>
    </div>
  )
}
